apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cd-template
spec:
  params:
  - name: repository
    description: git repo 
    default: " "
  - name: branch
    description: git branch
    default: master
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cd-pipeline-run-
      spec:
        serviceAccountName: pipeline
        pipelineRef: 
          name: cd-pipeline-run-
        params:
        - name: repo-url
          value: $(tt.params.repository)
        - name: branch
          values: $(tt.params.branch)
